##### Задание 1

Импортируйте библиотеки pandas и numpy.
Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn. Создайте датафреймы X и y из этих данных.
Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test) с помощью функции train_test_split так, чтобы размер тестовой выборки
составлял 30% от всех данных, при этом аргумент random_state должен быть равен 42.
Создайте модель линейной регрессии под названием lr с помощью класса LinearRegression из модуля sklearn.linear_model.
Обучите модель на тренировочных данных (используйте все признаки) и сделайте предсказание на тестовых.
Вычислите R2 полученных предказаний с помощью r2_score из модуля sklearn.metrics.

In [93]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_boston

In [94]:
boston = load_boston()

In [95]:
data = boston["data"]
feature_names = boston["feature_names"]
target = boston["target"]

In [96]:
X = pd.DataFrame(data, columns=feature_names)

In [97]:
y = pd.DataFrame(target, columns=["price"])

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [100]:
from sklearn.linear_model import LinearRegression

In [101]:
lr = LinearRegression()

In [102]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [103]:
y_pred = lr.predict(X_test)

In [104]:
check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})

check_test.head(10)

     y_test     y_pred
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280
76     20.0  23.146689
316    17.8  17.392124
140    14.0  14.078599
471    19.6  23.036927
500    16.8  20.599433

In [105]:
from sklearn.metrics import r2_score

In [106]:
r2_score(y_test, y_pred)

0.711226005748496

##### Задание 2
Создайте модель под названием model с помощью RandomForestRegressor из модуля sklearn.ensemble.
Сделайте агрумент n_estimators равным 1000,
max_depth должен быть равен 12 и random_state сделайте равным 42.
Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression,
но при этом в метод fit вместо датафрейма y_train поставьте y_train.values[:, 0],
чтобы получить из датафрейма одномерный массив Numpy,
так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно применение массивов вместо датафрейма.
Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.
Напишите в комментариях к коду, какая модель в данном случае работает лучше.

In [107]:
from sklearn.ensemble import RandomForestRegressor

In [108]:
clf = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)

In [109]:
clf.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=12,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1000,
                      n_jobs=None, oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [110]:
y_pred = clf.predict(X_test)

In [111]:
check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})

check_test.head(10)

     y_test     y_pred
173    23.6  22.846138
274    32.4  31.156114
491    13.6  16.297226
72     22.8  23.821036
452    16.1  17.212148
76     20.0  21.820092
316    17.8  19.866369
140    14.0  14.759938
471    19.6  21.235224
500    16.8  20.883103

In [112]:
r2_score(y_test, y_pred)

0.8749965273218174

Вторая модель лучше, так как коэффициент детерминации ближе к единице.

### * Задание 3
Вызовите документацию для класса RandomForestRegressor,
найдите информацию об атрибуте feature_importances_.
С помощью этого атрибута найдите сумму всех показателей важности,
установите, какие два признака показывают наибольшую важность.

In [113]:
?RandomForestRegressor

In [114]:
clf.feature_importances_

array([0.03211748, 0.00154999, 0.0070941 , 0.0011488 , 0.01436832,
       0.40270459, 0.01424477, 0.06403265, 0.00496762, 0.01169177,
       0.01808961, 0.0123114 , 0.41567892])

In [115]:

feature_importance = pd.DataFrame({'name':X.columns, 
                                   'feature_importance':clf.feature_importances_}, 
                                  columns=['feature_importance', 'name'])
feature_importance

    feature_importance     name
0             0.032117     CRIM
1             0.001550       ZN
2             0.007094    INDUS
3             0.001149     CHAS
4             0.014368      NOX
5             0.402705       RM
6             0.014245      AGE
7             0.064033      DIS
8             0.004968      RAD
9             0.011692      TAX
10            0.018090  PTRATIO
11            0.012311        B
12            0.415679    LSTAT

In [116]:

feature_importance.nlargest(2, 'feature_importance')

    feature_importance   name
12            0.415679  LSTAT
5             0.402705     RM

##### *Задание 4
В этом задании мы будем работать с датасетом, с которым мы уже знакомы по домашнему заданию по библиотеке Matplotlib, это датасет Credit Card Fraud Detection.Для этого датасета мы будем решать задачу классификации - будем определять,какие из транзакциции по кредитной карте являются мошенническими.Данный датасет сильно несбалансирован (так как случаи мошенничества относительно редки),так что применение метрики accuracy не принесет пользы и не поможет выбрать лучшую модель.Мы будем вычислять AUC, то есть площадь под кривой ROC.
Импортируйте из соответствующих модулей RandomForestClassifier, GridSearchCV и train_test_split.
Загрузите датасет creditcard.csv и создайте датафрейм df.

In [117]:
df = pd.read_csv('creditcard.csv')

In [118]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

С помощью метода value_counts с аргументом normalize=True убедитесь в том, что выборка несбалансирована.Используя метод info, проверьте, все ли столбцы содержат числовые данные и нет ли в них пропусков.Примените следующую настройку, чтобы можно было просматривать все столбцы датафрейма:
pd.options.display.max_columns = 100.

In [119]:
for i in df:
    print(df[i].value_counts(normalize=True))

163152.0    0.000126
64947.0     0.000091
68780.0     0.000088
3767.0      0.000074
3770.0      0.000070
              ...
2088.0      0.000004
64100.0     0.000004
42068.0     0.000004
119630.0    0.000004
140344.0    0.000004
Name: Time, Length: 124592, dtype: float64
 2.055797    0.000270
 1.245674    0.000270
 2.053311    0.000218
 1.302378    0.000211
 2.040211    0.000186
               ...
-0.069327    0.000004
-1.619420    0.000004
 1.174923    0.000004
 2.157306    0.000004
 2.287784    0.000004
Name: V1, Length: 275663, dtype: float64
 0.166975    0.000270
-0.326668    0.000270
 0.089735    0.000218
-0.606529    0.000211
-0.146975    0.000186
               ...
 0.520114    0.000004
-0.419199    0.000004
-0.303794    0.000004
 0.167497    0.000004
-0.166213    0.000004
Name: V2, Length: 275663, dtype: float64
-2.752041    0.000270
 0.488306    0.000270
-1.681836    0.000218
-0.681986    0.000211
-2.955934    0.000186
               ...
-2.773663    0.000004
-2.148874    0.000004
 0.741123    0.000004
-2.696536    0.000004
 0.315988    0.000004
Name: V3, Length: 275663, dtype: float64
-0.842316    0.000270
 0.635322    0.000270
 0.454212    0.000218
-1.904603    0.000211
-0.578356    0.000186
               ...
 2.834682    0.000004
 0.564523    0.000004
-1.193373    0.000004
-0.711142    0.000004
 1.337592    0.000004
Name: V4, Length: 275663, dtype: float64
 2.463072    0.000270
-0.562777    0.000270
 0.298310    0.000218
 1.326623    0.000211
 2.609358    0.000186
               ...
-0.448828    0.000004
 0.250671    0.000004
-0.522516    0.000004
-0.649162    0.000004
 0.245159    0.000004
Name: V5, Length: 275663, dtype: float64
-1.011073    0.000270
 3.173856    0.000270
-0.953526    0.000218
 3.436312    0.000211
 3.142642    0.000186
               ...
 0.923729    0.000004
-0.616964    0.000004
-1.010584    0.000004
-1.296312    0.000004
 0.880804    0.000004
Name: V6, Length: 275663, dtype: float64
-0.432126    0.000270
 0.014953    0.000270
 0.152003    0.000218
-1.145127    0.000211
-0.416883    0.000186
               ...
-0.006237    0.000004
 0.697378    0.000004
 1.130880    0.000004
 0.573042    0.000004
 0.223989    0.000004
Name: V7, Length: 275663, dtype: float64
-0.160211    0.000270
 0.727706    0.000270
-0.207071    0.000218
 0.959147    0.000211
 0.784393    0.000186
               ...
 0.294229    0.000004
-0.175237    0.000004
 1.829112    0.000004
 0.027999    0.000004
 0.407707    0.000004
Name: V8, Length: 275663, dtype: float64
 0.170362    0.000270
 0.608606    0.000270
 0.587335    0.000218
 1.671302    0.000211
 0.359902    0.000186
               ...
 0.340422    0.000004
 1.963203    0.000004
-0.763159    0.000004
 1.344202    0.000004
-0.562424    0.000004
Name: V9, Length: 275663, dtype: float64
-0.044575    0.000270
-0.075186    0.000270
-0.362047    0.000218
-1.022946    0.000211
-0.351075    0.000186
               ...
-0.936097    0.000004
-1.625618    0.000004
 0.346382    0.000004
 0.059576    0.000004
-0.500907    0.000004
Name: V10, Length: 275663, dtype: float64
-0.356749    0.000270
 0.063504    0.000270
-0.589598    0.000218
-0.191423    0.000211
 0.329651    0.000186
               ...
 1.041802    0.000004
-0.685356    0.000004
-0.028580    0.000004
-1.010640    0.000004
 0.967952    0.000004
Name: V11, Length: 275663, dtype: float64
 0.350564    0.000270
-0.073460    0.000270
-0.174712    0.000218
 0.631027    0.000211
 0.183508    0.000186
               ...
 1.026525    0.000004
-0.331234    0.000004
-0.046139    0.000004
-1.581549    0.000004
 0.130028    0.000004
Name: V12, Length: 275663, dtype: float64
-0.141238    0.000270
-0.517760    0.000270
-0.621127    0.000218
 0.031907    0.000211
-0.272919    0.000186
               ...
-0.958312    0.000004
 0.973101    0.000004
 1.076993    0.000004
-1.576917    0.000004
-0.554410    0.000004
Name: V13, Length: 275663, dtype: float64
 0.406969    0.000270
 0.690972    0.000270
-0.703513    0.000218
-0.031425    0.000211
-0.597437    0.000186
               ...
 2.217835    0.000004
 0.087633    0.000004
-0.383463    0.000004
-0.311812    0.000004
 0.065041    0.000004
Name: V14, Length: 275663, dtype: float64
 1.275257    0.000270
 1.124147    0.000270
 0.271957    0.000218
 1.446627    0.000211
 0.583897    0.000186
               ...
 1.274643    0.000004
-0.038291    0.000004
 0.391338    0.000004
 0.924640    0.000004
-0.718351    0.000004
Name: V15, Length: 275663, dtype: float64
 0.342470    0.000270
-0.371962    0.000270
 0.318688    0.000218
-0.121820    0.000211
 0.178676    0.000186
               ...
 2.091242    0.000004
 1.459761    0.000004
-0.874506    0.000004
-1.870238    0.000004
-0.705987    0.000004
Name: V16, Length: 275663, dtype: float64
-0.601957    0.000270
-0.374656    0.000270
 0.549365    0.000218
-0.651405    0.000211
 0.473898    0.000186
               ...
 0.244724    0.000004
-0.273306    0.000004
 0.700591    0.000004
-0.511246    0.000004
 1.038161    0.000004
Name: V17, Length: 275663, dtype: float64
-0.438992    0.000270
-0.052640    0.000270
-0.257786    0.000218
 0.617970    0.000211
-0.498850    0.000186
               ...
-0.221214    0.000004
-0.394483    0.000004
-0.047950    0.000004
 0.999119    0.000004
 0.160657    0.000004
Name: V18, Length: 275663, dtype: float64
-0.116091    0.000270
-0.330590    0.000270
 0.016256    0.000218
 0.927600    0.000211
-0.140099    0.000186
               ...
 0.048920    0.000004
 0.279753    0.000004
-0.772876    0.000004
 0.867389    0.000004
-0.342077    0.000004
Name: V19, Length: 275663, dtype: float64
-0.180370    0.000270
-0.132080    0.000270
-0.187421    0.000218
 0.005757    0.000211
-0.120714    0.000186
               ...
-0.522196    0.000004
 0.003292    0.000004
-0.006174    0.000004
 0.153984    0.000004
-0.113892    0.000004
Name: V20, Length: 275663, dtype: float64
-0.262581    0.000270
 0.269765    0.000270
-0.361158    0.000218
-0.064208    0.000211
-0.352334    0.000186
               ...
 0.254958    0.000004
 0.234337    0.000004
-0.771736    0.000004
-0.100244    0.000004
-0.217489    0.000004
Name: V21, Length: 275663, dtype: float64
-0.816264    0.000270
 0.844627    0.000270
-0.984262    0.000218
-0.080587    0.000211
-0.996937    0.000186
               ...
-1.052507    0.000004
-1.893226    0.000004
 0.087224    0.000004
-0.572146    0.000004
-0.126533    0.000004
Name: V22, Length: 275663, dtype: float64
 0.140304    0.000270
 0.020675    0.000270
 0.354198    0.000218
-0.072991    0.000211
 0.363485    0.000186
               ...
-0.315148    0.000004
-0.062703    0.000004
 0.143031    0.000004
-0.184059    0.000004
 0.016187    0.000004
Name: V23, Length: 275663, dtype: float64
 0.726212    0.000270
 0.357827    0.000270
 0.620709    0.000218
 1.018136    0.000211
 0.604827    0.000186
               ...
-0.316948    0.000004
 0.400848    0.000004
 0.271161    0.000004
-0.016787    0.000004
 0.606096    0.000004
Name: V24, Length: 275663, dtype: float64
 0.186423    0.000270
 0.366624    0.000270
-0.297138    0.000218
 0.663575    0.000211
-0.264560    0.000186
               ...
 0.476901    0.000004
-0.207339    0.000004
-0.003946    0.000004
 0.825100    0.000004
-0.236037    0.000004
Name: V25, Length: 275663, dtype: float64
-0.398828    0.000270
 0.096544    0.000270
 0.166736    0.000218
-0.671323    0.000211
 0.219671    0.000186
               ...
 0.407455    0.000004
 0.020841    0.000004
 0.071845    0.000004
-0.789816    0.000004
 0.615747    0.000004
Name: V26, Length: 275663, dtype: float64
 0.027735    0.000270
-0.035866    0.000270
-0.068299    0.000218
 0.096801    0.000211
-0.039209    0.000186
               ...
 0.182972    0.000004
-0.010605    0.000004
-0.237391    0.000004
-0.025269    0.000004
-1.084269    0.000004
Name: V27, Length: 275663, dtype: float64
 0.018495    0.000270
-0.060282    0.000270
-0.029585    0.000218
 0.028697    0.000211
-0.042787    0.000186
               ...
-0.101761    0.000004
 0.050051    0.000004
-0.006572    0.000004
-0.226909    0.000004
-0.030777    0.000004
Name: V28, Length: 275663, dtype: float64
1.00       0.048061
1.98       0.021221
0.89       0.017106
9.99       0.016667
15.00      0.011517
             ...
192.63     0.000004
218.84     0.000004
195.52     0.000004
793.50     0.000004
1080.06    0.000004
Name: Amount, Length: 32767, dtype: float64

0    0.998273
1    0.001727
Name: Class, dtype: float64

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26       284807 non-null float64
V27       284807 non-null float64
V28       284807 non-null float64
Amount    284807 non-null float64
Class     284807 non-null int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [121]:
pd.options.display.max_columns = 100


Просмотрите первые 10 строк датафрейма df.
Создайте датафрейм X из датафрейма df, исключив столбец Class.
Создайте объект Series под названием y из столбца Class.
Разбейте X и y на тренировочный и тестовый наборы данных при помощи функции train_test_split, используя аргументы: test_size=0.3, random_state=100, stratify=y.
У вас должны получиться объекты X_train, X_test, y_train и y_test.
Просмотрите информацию о их форме.

In [122]:

df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,1.341262,0.359894,-0.358091,-0.137134,0.517617,0.401726,-0.058133,0.068653,-0.033194,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,-1.416907,-0.153826,-0.751063,0.167372,0.050144,-0.443587,0.002821,-0.611987,-0.045575,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,1.249376,-0.619468,0.291474,1.757964,-1.323865,0.686133,-0.076127,-1.222127,-0.358222,0.324505,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,-0.705117,-0.110452,-0.286254,0.074355,-0.328783,-0.210077,-0.499768,0.118765,0.570328,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,1.017614,0.836390,1.006844,-0.443523,0.150219,0.739453,-0.540980,0.476677,0.451773,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [123]:
X = df.drop('Class', axis=1)

In [124]:

y = df['Class']

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)

In [126]:
for i in (X_train, X_test, y_train, y_test):
    print(i.shape)

(199364, 30)
(85443, 30)
(199364,)
(85443,)

Для поиска по сетке параметров задайте такие параметры:
parameters = [{'n_estimators': [10, 15],
'max_features': np.arange(3, 5),
'max_depth': np.arange(4, 7)}]
Создайте модель GridSearchCV со следующими аргументами:
estimator=RandomForestClassifier(random_state=100),
param_grid=parameters,
scoring='roc_auc',
cv=3.
Обучите модель на тренировочном наборе данных (может занять несколько минут).
Просмотрите параметры лучшей модели с помощью атрибута best_params_.
Предскажите вероятности классов с помощью полученнной модели и метода predict_proba.

In [127]:
parameters = [{
    'n_estimators': [10, 15], 
    'max_features': np.arange(3, 5), 
    'max_depth': np.arange(4, 7)
}]

In [128]:
clf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=100),
    param_grid=parameters,
    scoring='roc_auc',
    cv=3,
)

In [129]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False, random_state=100,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'max_depth': array([4, 5, 6]),
                          'max_features': array([3, 4]),
                          'n_estimators': [10, 15]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [130]:
clf.best_params_

{'max_depth': 6, 'max_features': 3, 'n_estimators': 15}

In [131]:
clf = RandomForestClassifier(max_depth=6, max_features=3, n_estimators=15)

clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features=3, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=15,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [132]:
y_pred = clf.predict_proba(X_test)

Из полученного результата (массив Numpy) выберите столбец с индексом 1 (вероятность класса 1) и запишите в массив y_pred_proba. Из модуля sklearn.metrics импортируйте метрику roc_auc_score.
Вычислите AUC на тестовых данных и сравните с результатом,полученным на тренировочных данных, используя в качестве аргументовмассивы y_test и y_pred_proba.

In [133]:
y_pred_proba = y_pred[:, 1]

In [134]:
from sklearn.metrics import roc_auc_score

In [135]:
roc_auc_score(y_test, y_pred_proba)

0.9602549102241347

#### *Дополнительные задания:
1). Загрузите датасет Wine из встроенных датасетов sklearn.datasets с помощью функции load_wine в переменную data.

In [136]:
from sklearn.datasets import load_wine
data = load_wine()

2). Полученный датасет не является датафреймом. Это структура данных, имеющая ключи аналогично словарю. Просмотрите тип данных этой структуры данных и создайте список data_keys, содержащий ее ключи.

In [139]:
type(data)

sklearn.utils.Bunch

In [156]:
data_keys = data.keys()
print(data_keys)

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

3). Просмотрите данные, описание и названия признаков в датасете. Описание нужно вывести в виде привычного, аккуратно оформленного текста, без обозначений переноса строки, но с самими переносами и т.д.4). Сколько классов содержит целевая переменная датасета? Выве
дите названия классов.

In [174]:
print(data.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]

In [170]:
print(data.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2

    :Summary Statistics:

    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners:

Forina, M. et al, PARVUS -
An Extendible Package for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science.

.. topic:: References

  (1) S. Aeberhard, D. Coomans and O. de Vel,
  Comparison of Classifiers in High Dimensional Settings,
  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Technometrics).

  The data was used with many others for comparing various
  classifiers. The classes are separable, though only RDA
  has achieved 100% correct classification.
  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))
  (All results using the leave-one-out technique)

  (2) S. Aeberhard, D. Coomans and O. de Vel,
  "THE CLASSIFICATION PERFORMANCE OF RDA"
  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Journal of Chemometrics).

In [171]:
print(set(data.target))
print(len(set(data.target)))

{0, 1, 2}
3

In [172]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

5). На основе данных датасета (они содержатся в двумерном массиве Numpy) и названий признаков создайте датафрейм под названием X.

In [175]:
X = pd.DataFrame(data.data, columns=data.feature_names)
X.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

6). Выясните размер датафрейма X и установите, имеются ли в нем пропущенные значения.

In [176]:
X.shape

(178, 13)

In [177]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
dtypes: float64(13)
memory usage: 18.2 KB

7). Добавьте в датафрейм поле с классами вин в виде чисел, имеющих тип данных numpy.int64. Название поля - 'target'.

In [196]:
X['target'] = data.target

In [197]:
X.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [198]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
target                          178 non-null int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

8). Постройте матрицу корреляций для всех полей X. Дайте полученному датафрейму название X_corr.

In [199]:
X_corr = X.corr()
X_corr

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
alcohol,1.000000,0.094397,0.211545,-0.310235,0.270798,0.289101,0.236815,-0.155929,0.136698,0.546364,-0.071747,0.072343,0.643720,-0.328222
malic_acid,0.094397,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011,0.437776
ash,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626,-0.049643
alcalinity_of_ash,-0.310235,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597,0.517859
magnesium,0.270798,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351,-0.209179
total_phenols,0.289101,-0.335167,0.128980,-0.321113,0.214401,1.000000,0.864564,-0.449935,0.612413,-0.055136,0.433681,0.699949,0.498115,-0.719163
flavanoids,0.236815,-0.411007,0.115077,-0.351370,0.195784,0.864564,1.000000,-0.537900,0.652692,-0.172379,0.543479,0.787194,0.494193,-0.847498
nonflavanoid_phenols,-0.155929,0.292977,0.186230,0.361922,-0.256294,-0.449935,-0.537900,1.000000,-0.365845,0.139057,-0.262640,-0.503270,-0.311385,0.489109
proanthocyanins,0.136698,-0.220746,0.009652,-0.197327,0.236441,0.612413,0.652692,-0.365845,1.000000,-0.025250,0.295544,0.519067,0.330417,-0.499130
color_intensity,0.546364,0.248985,0.258887,0.018732,0.199950,-0.055136,-0.172379,0.139057,-0.025250,1.000000,-0.521813,-0.428815,0.316100,0.265668
hue,-0.071747,-0.561296,-0.074667,-0.273955,0.055398,0.433681,0.543479,-0.262640,0.295544,-0.521813,1.000000,0.565468,0.236183,-0.617369
od280/od315_of_diluted_wines,0.072343,-0.368710,0.003911,-0.276769,0.066004,0.699949,0.787194,-0.503270,0.519067,-0.428815,0.565468,1.000000,0.312761,-0.788230
proline,0.643720,-0.192011,0.223626,-0.440597,0.393351,0.498115,0.494193,-0.311385,0.330417,0.316100,0.236183,0.312761,1.000000,-0.633717
target,-0.328222,0.437776,-0.049643,0.517859,-0.209179,-0.719163,-0.847498,0.489109,-0.499130,0.265668,-0.617369,-0.788230,-0.633717,1.000000

9). Создайте список high_corr из признаков, корреляция которых с полем target по абсолютному значению превышает 0.5 (причем, само поле target не должно входить в этот список).

In [208]:
high_corr = X_corr.loc[(abs(X_corr['target']) > 0.5) & (X_corr.index != 'target'), : ].index
high_corr

Index(['alcalinity_of_ash', 'total_phenols', 'flavanoids', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

10). Удалите из датафрейма X поле с целевой переменной. Для всех признаков, названия которых содержатся в списке high_corr, вычислите квадрат их значений и добавьте в датафрейм X соответствующие поля с суффиксом '_2', добавленного к первоначальному названию признака. Итоговый датафрейм должен содержать все поля, которые, были в нем изначально, а также поля с признаками из списка high_corr, возведенными в квадрат. Выведите описание полей датафрейма X с помощью метода describe.

In [209]:
X = X.drop('target', axis=1)
X.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [214]:
for feature in high_corr:
    X[f'{feature}_2'] = X.apply(lambda row: row[feature_name] ** 2, axis=1)

In [215]:
X.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,alcalinity_of_ash_2,total_phenols_2,flavanoids_2,hue_2,od280/od315_of_diluted_wines_2,proline_2
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,6.564591e+05,6.564591e+05,6.564591e+05,6.564591e+05,6.564591e+05,6.564591e+05
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,5.558591e+05,5.558591e+05,5.558591e+05,5.558591e+05,5.558591e+05,5.558591e+05
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,7.728400e+04,7.728400e+04,7.728400e+04,7.728400e+04,7.728400e+04,7.728400e+04
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,2.505010e+05,2.505010e+05,2.505010e+05,2.505010e+05,2.505010e+05,2.505010e+05
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,4.536045e+05,4.536045e+05,4.536045e+05,4.536045e+05,4.536045e+05,4.536045e+05
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,9.702250e+05,9.702250e+05,9.702250e+05,9.702250e+05,9.702250e+05,9.702250e+05
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.822400e+06,2.822400e+06,2.822400e+06,2.822400e+06,2.822400e+06,2.822400e+06